name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Use a stable version

      # Deploy to Server
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.HOST_DNS}}
          key: ${{secrets.EC2_SSH_KEY}}
          username: ${{secrets.USERNAME}}
          script: |
            echo "Starting deployment..."

            # Install required packages if not present
            sudo apt-get update
            sudo apt-get install -y python3-venv

            # Create or navigate to project directory
            mkdir -p ~/fastapi-book-project
            cd ~/fastapi-book-project

            # Initialize git if needed
            if [ ! -d .git ]; then
              git init
              git remote add origin https://github.com/Reaganz-Wat/fastapi-book-project.git
              git fetch
              git checkout main
            fi

            # Pull latest changes
            echo "Pulling latest changes..."
            git fetch --all
            git reset --hard origin/main

            # Setup virtual environment
            echo "Setting up virtual environment..."
            python3 -m venv venv
            source venv/bin/activate

            # Upgrade pip and install dependencies
            python -m pip install --upgrade pip
            pip install fastapi
            echo "FastAPI installed successfully"
            pip install -r requirements.txt

            # Stop existing application if running
            echo "Stopping existing application..."
            pkill uvicorn || echo "No existing process found"
            echo "Application stopped successfully"

            # Start application
            echo "Starting application..."
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &
            echo "Application started successfully"